module.exports = [
  (text: '{.acyclic.}', description: ' '),
  (text: '{.asmNoStackFrame.}', description: ' '),
  (text: '{.assertions.}', description: ' ', params: true),
  (text: '{.base.}', description: ' ', params: true),
  (text: '{.borrow.}', description: ' ', params: true),
  (text: '{.boundsChecks.}', description: ' ', params: true),
  (text: '{.bycopy.}', description: ' '),
  (text: '{.byref.}', description: ' '),
  (text: '{.callConv.}', description: ' ', params: true),
  (text: '{.cdecl.}', description: ' '),
  (text: '{.checks.}', description: ' ', params: true),
  (text: '{.closure.}', description: ' '),
  (text: '{.compileTime.}', description: ' '),
  (text: '{.computedGoto.}', description: ' '),
  (text: '{.deadCodeElim.}', description: ' '),
  (text: '{.deprecated.}', description: ' '),
  (text: '{.destructor.}', description: ' '),
  (text: '{.discardable.}', description: ' '),
  (text: '{.dynlib.}', description: ' ', params: true),
  (text: '{.effects.}', description: ' '),
  (text: '{.error.}', description: ' '),
  (text: '{.experimental.}', description: ' '),
  (text: '{.exportc.}', description: ' ', params: true),
  (text: '{.extern.}', description: ' ', params: true),
  (text: '{.fatal.}', description: ' '),
  (text: '{.final.}', description: ' '),
  (text: '{.global.}', description: ' '),
  (text: '{.header.}', description: ' ', params: true),
  (text: '{.hint.}', description: ' '),
  #(text: '{.hints.}', description: ' ', params: true),
  (text: '{.immediate.}', description: ' '),
  (text: '{.importc.}', description: ' ', params: true),
  (text: '{.inheritable.}', description: ' '),
  (text: '{.InfChecks.}', description: ' ', params: true),
  (text: '{.inline.}', description: ' '),
  (text: '{.line.}', description: ' '),
  (text: '{.linearScanEnd.}', description: ' '),
  (text: '{.locks.}', description: ' ', params: true),
  (text: '{.NaNChecks.}', description: ' ', params: true),
  (text: '{.nilChecks.}', description: ' ', params: true),
  (text: '{.noinit.}', description: ' '),
  (text: '{.noSideEffect.}', description: ' '),
  (text: '{.optimization.}', description: ' ', params: true),
  (text: '{.overflowChecks.}', description: ' ', params: true),
  (text: '{.override.}', description: ' '),
  (text: '{.noReturn.}', description: ' '),
  (text: '{.packed.}', description: ' ', params: true),
  (text: '{.patterns.}', description: ' ', params: true),
  (text: '{.pop.}', description: ' '),
  (text: '{.pragma.}', description: ' '),
  (text: '{.procvar.}', description: ' '),
  (text: '{.pure.}', description: ' '),
  (text: '{.push.}', description: ' '),
  (text: '{.register.}', description: ' '),
  (text: '{.requiresinit.}', description: ' '),
  (text: '{.shallow.}', description: ' '),
  (text: '{.thread.}', description: ' '),
  (text: '{.threadvar.}', description: ' '),
  (text: '{.unchecked.}', description: ' ')
  (text: '{.union.}', description: ' ')
  (text: '{.unroll.}', description: ' '),
  (text: '{.varargs.}', description: ' ')
  (text: '{.warning.}', description: ' ')
  #(text: '{.warnings.}', description: ' ', params: true),
]
